// <auto-generated />
using System;
using LogicaAccesoDatos.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaAccesoDatos.Migrations
{
    [DbContext(typeof(StellarMindsContext))]
    [Migration("20260525125000_AuditoriasPrestamos")]
    partial class AuditoriasPrestamos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditoriaPrestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accion")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditoriasPrestamos");
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Equipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.ObjetoCeleste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MagnitudAparente")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ObjetosCelestes");
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.Observacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Indicador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObjetoCelesteId")
                        .HasColumnType("int");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjetoCelesteId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("Observaciones");
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CamaraId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonturaId")
                        .HasColumnType("int");

                    b.Property<int?>("OcularId")
                        .HasColumnType("int");

                    b.Property<int>("TelescopioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CamaraId");

                    b.HasIndex("MonturaId");

                    b.HasIndex("OcularId");

                    b.HasIndex("TelescopioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.Camara", b =>
                {
                    b.HasBaseType("LogicaNegocio.ClasesDominio.Equipo");

                    b.Property<string>("Resolucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TamanoPixelUm")
                        .HasColumnType("float");

                    b.Property<int>("TipoSensor")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camara");
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.Montura", b =>
                {
                    b.HasBaseType("LogicaNegocio.ClasesDominio.Equipo");

                    b.Property<double>("CargaMaximaKg")
                        .HasColumnType("float");

                    b.Property<bool>("EsGoTo")
                        .HasColumnType("bit");

                    b.Property<int>("TipoMontura")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Montura");
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.Ocular", b =>
                {
                    b.HasBaseType("LogicaNegocio.ClasesDominio.Equipo");

                    b.Property<double>("CampoVisualGrados")
                        .HasColumnType("float");

                    b.Property<double>("DiametroMm")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Ocular");
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.Telescopio", b =>
                {
                    b.HasBaseType("LogicaNegocio.ClasesDominio.Equipo");

                    b.Property<int>("AperturaMm")
                        .HasColumnType("int");

                    b.Property<int>("DistanciaFocalMm")
                        .HasColumnType("int");

                    b.Property<double>("PesoKg")
                        .HasColumnType("float");

                    b.Property<double>("RelacionFocal")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Telescopio");
                });

            modelBuilder.Entity("AuditoriaPrestamo", b =>
                {
                    b.HasOne("LogicaNegocio.ClasesDominio.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.ClasesDominio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.Observacion", b =>
                {
                    b.HasOne("LogicaNegocio.ClasesDominio.ObjetoCeleste", "ObjetoCeleste")
                        .WithMany()
                        .HasForeignKey("ObjetoCelesteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.ClasesDominio.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjetoCeleste");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.Prestamo", b =>
                {
                    b.HasOne("LogicaNegocio.ClasesDominio.Camara", "Camara")
                        .WithMany()
                        .HasForeignKey("CamaraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogicaNegocio.ClasesDominio.Montura", "Montura")
                        .WithMany()
                        .HasForeignKey("MonturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.ClasesDominio.Ocular", "Ocular")
                        .WithMany()
                        .HasForeignKey("OcularId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogicaNegocio.ClasesDominio.Telescopio", "Telescopio")
                        .WithMany()
                        .HasForeignKey("TelescopioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.ClasesDominio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camara");

                    b.Navigation("Montura");

                    b.Navigation("Ocular");

                    b.Navigation("Telescopio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LogicaNegocio.ClasesDominio.Usuario", b =>
                {
                    b.HasOne("LogicaNegocio.ClasesDominio.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LogicaNegocio.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("LogicaNegocio.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
